server.port=${PORT:8080}
spring.application.name=auth-service

jwt.secret=${JWT_SECRET:AgryCamSecuriseCleJWT2026UniversiteDschang}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

logging.level.com.agrycam.authservice=DEBUG
logging.level.org.springframework.security=INFO

services.utilisateur-service.url=${UTILISATEUR_SERVICE_URL:http://localhost:8081}

# Doit correspondre a internal.service.secret dans utilisateur-service
internal.service.secret=${INTERNAL_SERVICE_SECRET:AgryCamInterneCleServiceASecretiser2026}

# Eureka Client - enregistrement aupres du serveur de decouverte AGRYCAM
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
