# ===================================================================
# Configuration de l'application Eureka Server - Projet AGRYCAM
# ===================================================================

# Nom du microservice
spring.application.name=eureka-server

# Port d'écoute du serveur Eureka (Port par défaut de l'écosystème : 8761)
server.port=${PORT:8761}

# Indique si ce serveur d'annuaire doit s'enregistrer auprès d'un autre serveur Eureka.
# Étant nous-mêmes le serveur principal autonome, on désactive cette option (false).
eureka.client.register-with-eureka=false

# Indique si ce service doit récupérer l'annuaire depuis un autre serveur.
# Comme nous sommes le serveur de référence, on désactive cette option (false).
eureka.client.fetch-registry=false

# Désactive le mode d'auto-préservation (self-preservation).
# Recommandé en environnement de développement ou instance unique pour éviter de garder
# actifs de faux positifs de microservices déconnectés.
# À réactiver en production avec plusieurs instances.
eureka.server.enable-self-preservation=false

# Nom de l'hôte associé au serveur Eureka (localhost par défaut)
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

# ===================================================================
# Configuration Actuator (Optionnel - Pour le suivi de la santé)
# ===================================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
