# Serveur
server.port=${PORT:8087}
spring.application.name=paiement-service

# Base de données
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/paiement_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:2026}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL des autres services
commande.service.url=${COMMANDE_SERVICE_URL:http://localhost:8088}
utilisateur.service.url=${UTILISATEUR_SERVICE_URL:http://localhost:8081}

# JWT
jwt.secret=${JWT_SECRET:AgryCamSecuriseCleJWT2026UniversiteDschang}
jwt.expiration=${JWT_EXPIRATION:86400000}